In [2]:
# 필요 라이브러리 다운로드
import numpy as np
import tensorflow as tf
from numpy import array
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense,Flatten,Embedding

In [3]:
# 텍스트  전처리를 담당하는 라이브러리
from keras.preprocessing.text import text_to_word_sequence

In [4]:
# 전처리할 텍스트를 정합니다.
text = "도전하지 않으면 해낼 수 없다"

In [5]:
# 해당 텍스트를 토근화
result = text_to_word_sequence(text)
print(f"원문 : {text}\n토큰화 : {result}")

원문 : 도전하지 않으면 해낼 수 없다
토큰화 : ['도전하지', '않으면', '해낼', '수', '없다']


In [6]:
# 전처리 하려는 문장
docs = [
        '먼저 텍스트의 각 단어를 나누어 토큰화 합니다.'
        ,'토큰화 함수를 적용해야 딥러닝에서 인식합니다.'
        ,'토근화 한 결과는 딥러닝에서 사용 할 수 있습니다.'
]

In [7]:
token = Tokenizer() 
token.fit_on_texts(docs) # 토큰화 함수적용

In [8]:
# 단어의 빈도수를 계산한 결과를 가 ㄱ옵션에 맞추어 출력
print(f'단어카운트:{token.word_counts}')

단어카운트:OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 2), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식합니다', 1), ('토근화', 1), ('한', 1), ('결과는', 1), ('사용', 1), ('할', 1), ('수', 1), ('있습니다', 1)])


In [9]:
print(f'문장 카운트 : {token.document_count}')
print(f'각 단어가 몇개의 문장에 포함되어 있는가 : {token.word_docs}')
print(f'각 단어에 매겨진 인덱스 값 : {token.word_index}')

문장 카운트 : 3
각 단어가 몇개의 문장에 포함되어 있는가 : defaultdict(<class 'int'>, {'각': 1, '텍스트의': 2, '먼저': 1, '합니다': 1, '단어를': 1, '나누어': 1, '토큰화': 2, '단어로': 1, '해야': 1, '인식합니다': 1, '딥러닝에서': 2, '결과는': 1, '한': 1, '사용': 1, '있습니다': 1, '토근화': 1, '할': 1, '수': 1})
각 단어에 매겨진 인덱스 값 : {'텍스트의': 1, '토큰화': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식합니다': 11, '토근화': 12, '한': 13, '결과는': 14, '사용': 15, '할': 16, '수': 17, '있습니다': 18}


In [10]:
# 텍스트의 리뷰 자료
doc=["너무 재미있네요","최고에요","참 잘 만든 영화입니다.","추천하고 싶은 영화 입니다.",'한번 더 보고싶네요','글쎄요'
,'별루예요','생각보다 지루하네요']
# 긍정리뷰는 1, 부정리뷰는 0으로 클래스를 지정
classes = array([1,1,1,1,1,0,0,0])

In [31]:
#토큰화
token = Tokenizer()
token.fit_on_texts(doc)
print(token.word_index)
x = token.texts_to_sequences(doc)
print(f"리뷰텍스트를 토근화 결과 : {x}")

{'너무': 1, '재미있네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화입니다': 7, '추천하고': 8, '싶은': 9, '영화': 10, '입니다': 11, '한번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별루예요': 16, '생각보다': 17, '지루하네요': 18}
리뷰텍스트를 토근화 결과 : [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14], [15], [16], [17, 18]]


In [32]:
# 패딩.. 서로다른 길이의 데이터를 4로 맞추어 줍니다. 
padded_x = pad_sequences(x,4)
print(f"패딩결과 : {padded_x}")

패딩결과 : [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]]


In [21]:
# 딥러닝 시작
# 임베딩에 입력될 단어의 수를 지정
word_size =  len(token.word_index)+1
word_size

19

In [33]:
padded_x, classes

(array([[ 0,  0,  1,  2],
        [ 0,  0,  0,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0, 12, 13, 14],
        [ 0,  0,  0, 15],
        [ 0,  0,  0, 16],
        [ 0,  0, 17, 18]], dtype=int32), array([1, 1, 1, 1, 1, 0, 0, 0]))

In [36]:
#단어이베딩을 포함해서 딥러닝 모델을 만들고 결과를 출력
model = Sequential()
model.add(Embedding(word_size,8,input_length=4))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 4, 8)              152       
                                                                 
 flatten_5 (Flatten)         (None, 32)                0         
                                                                 
 dense_5 (Dense)             (None, 1)                 33        
                                                                 
Total params: 185
Trainable params: 185
Non-trainable params: 0
_________________________________________________________________


In [37]:
padded_x.shape, classes.shape

((8, 4), (8,))

In [38]:
model.fit(padded_x,classes,epochs=20)
print("Accuracy: %.4f"%(model.evaluate(padded_x,classes)[1] ) )

Epoch 1/20
1/1 [==============================] - 1s 823ms/step - loss: 0.6982 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6963 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 12ms/step - loss: 0.6943 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6924 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 18ms/step - loss: 0.6905 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6885 - accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6866 - accuracy: 0.6250
Epoch 8/20
1/1 [==============================] - 0s 20ms/step - loss: 0.6847 - accuracy: 0.6250
Epoch 9/20
1/1 [==============================] - 0s 15ms/step - loss: 0.6828 - accuracy: 0.6250
Epoch 10/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6809 - accuracy: 0.6250
Epoch 11/20
1/1 [=============